version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  node_js_backend:
    build:
      context: .
      dockerfile: DockerFile
    container_name: nodejs_app_backend
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    links:
      - mongodb

  next_js_frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    container_name: nodejs_app_frontend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
